version: '3.6'
services:
  postgres:
    image: postgres:12
    restart: always
    volumes:
    - ./docker/db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgrespassword
