import type { GetServerSideProps, NextPage } from 'next'
import Head from 'next/head'
import Navbar from 'components/Layout/Navbar'

const Home: NextPage = () => {

  return (
    <>
      <Head>
        <title>Budget Tracker</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        Content
      </main>
    </>
  )
}

export default Home
